# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fe49f1382d0617d2b7407a15e38e63f77ba1e59781e07dc0d951226b3ed38eff3dd3a950da4eb1ee1bdf70f57f871bd1f01632a1bca4276e3cced380f39f6e9

test:
  secret_key_base: 81184202e0f1ac159ded09159acc414bdfbaf037786811ae3cb691eb84be4a8f9648fd74525afc4dbd19c4f47063f1b6576d47a54f985afb34999adfdde4c402

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
